import { defineConfig } from 'vitepress'

// The demo page is a Vite app: `npm run dev` serves it on :5173 next to
// this site on :5174, and the docs workflow builds it into <site>/demo/
// (`npm run demo:build`). In production the link is the absolute URL the
// workflow passes in, so VitePress's router does not treat it as a page.
const isDev = process.env.NODE_ENV !== 'production'
const demoUrl = isDev ? 'http://localhost:5173/demo/index.html' : process.env.DOCS_DEMO_URL
const liveDemos = demoUrl ? [{ text: '▶ Live demos', link: demoUrl }] : []

export default defineConfig({
  // GitHub Pages serves a project site under /jikz/; the docs workflow sets
  // DOCS_BASE. Local dev/build stay at the root.
  base: process.env.DOCS_BASE ?? '/',
  // The docs root and the cookbook are README.md so they read well on
  // GitHub; serve them as the directory index pages the nav links to
  // ('/' and '/cookbook/') instead of README.html.
  rewrites: {
    'README.md': 'index.md',
    'cookbook/README.md': 'cookbook/index.md',
  },
  title: 'jikz',
  description: 'TikZ-inspired coordinate and drawing library for JavaScript/TypeScript',
  // The TypeDoc output is generated by `npm run docs:api` into
  // docs/public/api, which VitePress copies verbatim, so the reference
  // pages' ../api/ links resolve on the published site.
  // Cookbook/tutorial pages link to ../../examples/*.ts, which live
  // outside the VitePress root — they're repo links, not site pages.
  ignoreDeadLinks: true,
  themeConfig: {
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Concepts', link: '/concepts/tikz-mapping' },
      { text: 'Tutorials', link: '/tutorials/01-first-picture' },
      { text: 'Reference', link: '/reference/picture' },
      { text: 'Cookbook', link: '/cookbook/' },
      ...liveDemos,
    ],
    sidebar: [
      {
        text: 'Concepts',
        items: [
          { text: 'TikZ → jikz mapping', link: '/concepts/tikz-mapping' },
          { text: 'Coordinate system', link: '/concepts/coordinate-system' },
          { text: 'Two API levels', link: '/concepts/two-api-levels' },
          { text: 'ViewBox, sizing & fit', link: '/concepts/viewbox-and-fit' },
          { text: 'Node, SSR & browser', link: '/concepts/node-ssr-browser' },
        ],
      },
      {
        text: 'Tutorials',
        items: [
          { text: '1. Your first picture', link: '/tutorials/01-first-picture' },
          { text: '2. Points & coordinates', link: '/tutorials/02-points-and-coordinates' },
          { text: '3. Nodes, anchors & labels', link: '/tutorials/03-nodes-anchors-labels' },
          { text: '4. Edges & routing', link: '/tutorials/04-edges-and-routing' },
          { text: '5. Paths & pen', link: '/tutorials/05-paths-and-pen' },
          { text: '6. Styling', link: '/tutorials/06-styling' },
          { text: '7. Layouts', link: '/tutorials/07-layouts' },
        ],
      },
      {
        text: 'Reference',
        items: [
          { text: 'picture', link: '/reference/picture' },
          { text: 'core', link: '/reference/core' },
          { text: 'geometry', link: '/reference/geometry' },
          { text: 'node', link: '/reference/node' },
          { text: 'path', link: '/reference/path' },
          { text: 'render', link: '/reference/render' },
          { text: 'layout', link: '/reference/layout' },
          { text: 'text & math', link: '/reference/text' },
          { text: 'ext/circuits', link: '/reference/ext-circuits' },
          { text: 'ext/dataviz', link: '/reference/ext-dataviz' },
        ],
      },
      {
        text: 'Cookbook',
        link: '/cookbook/',
      },
    ],
    socialLinks: [
      { icon: 'github', link: 'https://github.com/binboavetonik/jikz' },
      { icon: 'npm', link: 'https://www.npmjs.com/package/@ozan.e/jikz' },
    ],
  },
})
