import { defineConfig } from 'vitepress'
import { resolve } from 'node:path'

// KaTeX for the math-label example on the gallery (optional peer of the
// library; the example reads the global the script installs).
const KATEX = 'https://cdn.jsdelivr.net/npm/katex@0.16.11/dist'

export default defineConfig({
  // GitHub Pages serves a project site under /jikz/; the docs workflow sets
  // DOCS_BASE. Local dev/build stay at the root.
  base: process.env.DOCS_BASE ?? '/',
  // The site root is the live gallery (index.md). docs/README.md — the
  // GitHub-readable documentation map — is served at /overview/, and the
  // cookbook's README.md as its directory index, instead of README.html.
  rewrites: {
    'README.md': 'overview.md',
    'cookbook/README.md': 'cookbook/index.md',
  },
  head: [
    ['link', { rel: 'stylesheet', href: `${KATEX}/katex.min.css` }],
    ['script', { defer: '', src: `${KATEX}/katex.min.js` }],
  ],
  // The gallery renders examples/ against the live library source, exactly
  // as the examples import it (`from 'jikz'`).
  vite: {
    resolve: {
      alias: { jikz: resolve(__dirname, '../../src/index.ts') },
    },
  },
  title: 'jikz',
  description: 'TikZ-inspired coordinate and drawing library for JavaScript/TypeScript',
  // The TypeDoc output is generated by `npm run docs:api` into
  // docs/public/api, which VitePress copies verbatim to /api/. It is a
  // STATIC SITE, not a VitePress route, so the reference pages link to
  // it as `<a href="../api/index.html" target="_blank">`, and both
  // halves of that are load-bearing:
  //   - target="_blank" — VitePress's SPA router intercepts same-origin
  //     clicks and tries to resolve /api/ as one of ITS pages, which
  //     silently does nothing. The URL was always right; the click
  //     never landed. _blank is the documented opt-out.
  //   - /index.html, not the bare directory — `vitepress dev` has no
  //     directory-index fallback for public/ subdirectories, so /api/
  //     returns the empty SPA shell locally while /api/index.html
  //     serves the real page. A static host resolves both, so the
  //     explicit file is the form that works everywhere.
  // The href stays RELATIVE so it is correct under the project base
  // (/jikz/ on Pages) with no withBase() plumbing.
  // Cookbook/tutorial pages link to ../../examples/*.ts, which live
  // outside the VitePress root — they're repo links, not site pages.
  // The TypeDoc landing page (typedoc.json's `readme`) lives in the
  // docs root so it sits next to what it describes, but it is not a
  // page of THIS site — it is only ever rendered into /api/.
  srcExclude: ['api-readme.md'],
  ignoreDeadLinks: true,
  themeConfig: {
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Concepts', link: '/concepts/tikz-mapping' },
      { text: 'Tutorials', link: '/tutorials/01-first-picture' },
      { text: 'Reference', link: '/reference/picture' },
      { text: 'Cookbook', link: '/cookbook/' },
    ],
    sidebar: [
      { text: 'Gallery', link: '/' },
      {
        text: 'Start here',
        items: [
          { text: 'Overview', link: '/overview' },
          { text: 'Your first picture', link: '/tutorials/01-first-picture' },
        ],
      },
      {
        text: 'Concepts',
        items: [
          { text: 'TikZ → jikz mapping', link: '/concepts/tikz-mapping' },
          { text: 'Coordinate system', link: '/concepts/coordinate-system' },
          { text: 'Two API levels', link: '/concepts/two-api-levels' },
          { text: 'ViewBox, sizing & fit', link: '/concepts/viewbox-and-fit' },
          { text: 'Node, SSR & browser', link: '/concepts/node-ssr-browser' },
        ],
      },
      {
        text: 'Tutorials',
        items: [
          { text: '1. Your first picture', link: '/tutorials/01-first-picture' },
          { text: '2. Points & coordinates', link: '/tutorials/02-points-and-coordinates' },
          { text: '3. Nodes, anchors & labels', link: '/tutorials/03-nodes-anchors-labels' },
          { text: '4. Edges & routing', link: '/tutorials/04-edges-and-routing' },
          { text: '5. Paths & pen', link: '/tutorials/05-paths-and-pen' },
          { text: '6. Styling', link: '/tutorials/06-styling' },
          { text: '7. Layouts', link: '/tutorials/07-layouts' },
        ],
      },
      {
        text: 'Reference',
        items: [
          { text: 'picture', link: '/reference/picture' },
          { text: 'core', link: '/reference/core' },
          { text: 'geometry', link: '/reference/geometry' },
          { text: 'node', link: '/reference/node' },
          { text: 'path', link: '/reference/path' },
          { text: 'render', link: '/reference/render' },
          { text: 'layout', link: '/reference/layout' },
          { text: 'text & math', link: '/reference/text' },
          { text: 'ext/circuits', link: '/reference/ext-circuits' },
          { text: 'ext/dataviz', link: '/reference/ext-dataviz' },
          { text: 'ext/gates', link: '/reference/ext-gates' },
          { text: 'ext/petri', link: '/reference/ext-petri' },
        ],
      },
      {
        text: 'Cookbook',
        link: '/cookbook/',
      },
    ],
    socialLinks: [
      { icon: 'github', link: 'https://github.com/binboavetonik/jikz' },
      { icon: 'npm', link: 'https://www.npmjs.com/package/@ozan.e/jikz' },
    ],
  },
})
