/**
 * Cookbook generator — builds docs/cookbook/ from the example
 * registry:
 *
 *   - Renders every example headlessly (jsdom + the string pipeline)
 *     and writes a thumbnail SVG per card.
 *   - Regenerates docs/cookbook/README.md, categorized by the
 *     manifest's `category` field — so the cookbook can never drift
 *     from the gallery. Never edit the README by hand.
 *
 * Run: npm run docs:cookbook
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { JSDOM } from 'jsdom'
import { demos, CATEGORY_INFO } from '../examples/manifest'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT_DIR = join(ROOT, 'docs/cookbook')
const IMG_DIR = join(OUT_DIR, 'img')

const CATEGORY_ORDER = CATEGORY_INFO

// ── Render thumbnails through the string pipeline ───────────────────────────

const dom = new JSDOM('<!doctype html><html><body></body></html>')
// The library checks for a DOM via the globals — install jsdom's.
globalThis.document = dom.window.document as unknown as Document
globalThis.window = dom.window as unknown as Window & typeof globalThis
const document = dom.window.document

mkdirSync(IMG_DIR, { recursive: true })

for (const demo of demos) {
  const container = document.createElement('div')
  demo.render(container)
  const svg = container.innerHTML
  if (!svg.includes('<svg')) {
    throw new Error(`${demo.id}: render produced no SVG`)
  }
  writeFileSync(join(IMG_DIR, `${demo.id}.svg`), svg)
}
console.log(`rendered ${demos.length} thumbnails → docs/cookbook/img/`)

// ── Generate the cookbook page ──────────────────────────────────────────────

const lines: string[] = [
  '<!-- GENERATED by scripts/build-cookbook.ts — do not edit by hand. -->',
  '<!-- To change copy/order, edit examples/manifest.ts and regenerate. -->',
  '',
  '# Cookbook',
  '',
  'Every example in the gallery, organized by task — texample-style.',
  'Each card links its tested source in `examples/`; the thumbnails are',
  'rendered by that exact code (regenerate with `npm run docs:cookbook`).',
  '',
]

for (const [key, title, blurb] of CATEGORY_ORDER) {
  const group = demos.filter((d) => d.category === key)
  if (group.length === 0) continue
  lines.push(`## ${title}`, '', blurb, '')
  for (const demo of group) {
    // VitePress compiles markdown to a Vue SFC, so a raw `<tag>` outside a
    // code span becomes an unclosed element and breaks `docs:build`.
    // Catch it here, where the offending description is named.
    const outsideCode = demo.description.replace(/`[^`]*`/g, '')
    const rawTag = outsideCode.match(/<[a-zA-Z][^>\s]*/)
    if (rawTag) {
      throw new Error(
        `examples/manifest.ts: description of "" contains a raw > — ` +
          'wrap HTML/SVG element names in backticks so VitePress does not parse them as Vue elements',
      )
    }
    lines.push(
      `### ${demo.title}`,
      '',
      `![${demo.title}](img/${demo.id}.svg)`,
      '',
      demo.description,
      '',
      `**Source:** [\`examples/${demo.id}.ts\`](../../examples/${demo.id}.ts)`,
      '',
    )
  }
}

writeFileSync(join(OUT_DIR, 'README.md'), lines.join('\n'))
console.log(`wrote docs/cookbook/README.md (${demos.length} cards, ${CATEGORY_ORDER.length} categories)`)
